# This docker file is used for testing the image build
# Commands:
#   sudo docker build <path> -t <tag_name>  // Créer une image avec une étiquete
#   sudo docker images                      // Lister les images
#   sudo docker rmi <node>                  // Supprimer une image

FROM ubuntu:12.04
MAINTAINER Luxon JEAN-PIERRE <luxon.jean.pierre@gmail.com>
RUN echo ----------------------------------------------------------------------- && \
echo SUCCESS - Created the image \\\(^.^\)/ && \
echo -----------------------------------------------------------------------
